/**
 * web_index.h - Embedded HTML for admin interface
 *
 * Auto-generated from web/index.html
 * Do not edit manually - regenerate with: make web-embed
 */

"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>Linux File Server Admin</title>\n"
"    <style>\n"
"        body { font-family: monospace; background: #1a1a2e; color: #eee; padding: 20px; }\n"
"        .card { background: #16213e; border-radius: 8px; padding: 16px; margin: 10px 0; }\n"
"        h1 { color: #0f3460; }\n"
"        .stat { display: inline-block; margin: 10px 20px; }\n"
"        .stat-num { font-size: 2em; color: #e94560; }\n"
"        table { width: 100%; border-collapse: collapse; }\n"
"        td, th { padding: 8px; border-bottom: 1px solid #333; text-align: left; }\n"
"        .refresh { background: #e94560; color: white; border: none; padding: 8px 16px; cursor: pointer; border-radius: 4px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <h1>Linux File Server v2.0.0</h1>\n"
"    <button class=\"refresh\" onclick=\"refresh()\">Refresh</button>\n"
"\n"
"    <div class=\"card\">\n"
"        <h2>Statistics</h2>\n"
"        <div class=\"stat\"><div class=\"stat-num\" id=\"clients\">-</div><div>Clients</div></div>\n"
"        <div class=\"stat\"><div class=\"stat-num\" id=\"requests\">-</div><div>Requests</div></div>\n"
"        <div class=\"stat\"><div class=\"stat-num\" id=\"sent\">-</div><div>Bytes Sent</div></div>\n"
"        <div class=\"stat\"><div class=\"stat-num\" id=\"recv\">-</div><div>Bytes Recv</div></div>\n"
"    </div>\n"
"\n"
"    <div class=\"card\">\n"
"        <h2>Files</h2>\n"
"        <table>\n"
"            <thead><tr><th>Name</th><th>Size</th></tr></thead>\n"
"            <tbody id=\"file-list\"></tbody>\n"
"        </table>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        function refresh() {\n"
"            fetch('/api/stats').then(r=>r.json()).then(d => {\n"
"                document.getElementById('clients').textContent = d.client_count || 0;\n"
"                document.getElementById('requests').textContent = d.total_requests || 0;\n"
"                document.getElementById('sent').textContent = formatBytes(d.total_bytes_sent || 0);\n"
"                document.getElementById('recv').textContent = formatBytes(d.total_bytes_recv || 0);\n"
"            });\n"
"            fetch('/api/files').then(r=>r.json()).then(d => {\n"
"                let html = '';\n"
"                (d.files||[]).forEach(f => {\n"
"                    html += '<tr><td>'+f.name+'</td><td>'+formatBytes(f.size)+'</td></tr>';\n"
"                });\n"
"                document.getElementById('file-list').innerHTML = html || '<tr><td colspan=\"2\">No files</td></tr>';\n"
"            });\n"
"        }\n"
"        function formatBytes(b) {\n"
"            if(b<1024) return b+'B';\n"
"            if(b<1048576) return (b/1024).toFixed(1)+'KB';\n"
"            return (b/1048576).toFixed(1)+'MB';\n"
"        }\n"
"        refresh();\n"
"        setInterval(refresh, 5000);\n"
"    </script>\n"
"</body>\n"
"</html>\n"
